#!/bin/bash

BASE_URL="https://raw.githubusercontent.com/MichaelBorde/dotfiles/master"

program() {
  install_default
  install_options "$@"
}

install_options() {
  local option
  for option in $@; do
    install_option_if_valid "${option}"
  done
}

install_option_if_valid() {
  local option="${1}"
  local func="install_${option}"
  type "${func}" > /dev/null 2>&1
  if (( $? != 0 )); then
    echo "Option ${option} is invalid."
    exit 1
  else
    ${func}
  fi
}

install_default() {
  echo "Installing default dotfiles"
  download "profile/.zprofile"
  download "shellrc/.zshrc"
  download ".nanorc"
  download ".tmux.conf"
}

install_osx() {
  echo "Installing osx dotfiles"
  download "profile/.osxprofile"
  download "shellrc/.osxbashrc"
}

download() {
  local file="${1}"
  local name="${1//*\//}"
  curl -sSL -o "${HOME}/${name}" "${BASE_URL}/${file}"
}

program "$@"
