(global-set-key (kbd "C-c d") 'duplicate-current-line-or-region)
(global-set-key (kbd "C-z") 'undo)
(global-set-key (kbd "C-S-z") 'redo)
(global-set-key (kbd "C-c C-z") 'redo)
(global-set-key (kbd "C-c <up>") 'move-line-up)
(global-set-key (kbd "C-c <down>") 'move-line-down)
(global-set-key (kbd "C-c C-s") 'sr-speedbar-toggle)
(global-set-key (kbd "C-c C-i") 'ac-complete-with-helm)
(global-set-key (kbd "M-x") 'helm-M-x)
(global-set-key (kbd "M-y") 'helm-show-kill-ring)
(global-set-key (kbd "C-x b") 'helm-mini)
(global-set-key (kbd "C-x C-f") 'helm-find-files)
(global-set-key (kbd "C-x C-b") 'helm-buffers-list)
(global-set-key (kbd "C-c i b") 'indent-buffer)
